name: lab
channels:
  - defaults
dependencies:
  - blas=1.0=openblas
  - bzip2=1.0.8=h80987f9_6
  - ca-certificates=2025.7.15=hca03da5_0
  - expat=2.7.1=h313beb8_0
  - libcxx=20.1.8=h8869778_0
  - libffi=3.4.4=hca03da5_1
  - libgfortran=5.0.0=11_3_0_hca03da5_28
  - libgfortran5=11.3.0=h009349e_28
  - libopenblas=0.3.29=hea593b9_0
  - libzlib=1.3.1=h5f15de7_0
  - llvm-openmp=20.1.8=he822017_0
  - ncurses=6.5=hee39554_0
  - openssl=3.0.17=h4ee41c1_0
  - pip=25.2=pyhc872135_0
  - python=3.9.23=h99c0cbc_0
  - readline=8.3=h0b18652_0
  - setuptools=78.1.1=py39hca03da5_0
  - sqlite=3.50.2=h79febb2_1
  - tk=8.6.15=hcd8a7d5_0
  - tzdata=2025b=h04d1e81_0
  - wheel=0.45.1=py39hca03da5_0
  - xz=5.6.4=h80987f9_1
  - zlib=1.3.1=h5f15de7_0
  - pip:
      - absl-py==2.3.1
      - attrs==25.3.0
      - cffi==2.0.0
      - contourpy==1.3.0
      - cycler==0.12.1
      - flatbuffers==25.2.10
      - fonttools==4.59.2
      - importlib-metadata==8.7.0
      - importlib-resources==6.5.2
      - jax==0.4.30
      - jaxlib==0.4.30
      - kiwisolver==1.4.7
      - matplotlib==3.9.4
      - mediapipe==0.10.21
      - mido==1.3.3
      - ml-dtypes==0.5.3
      - numpy==1.26.4
      - opencv-contrib-python==4.11.0.86
      - opencv-python==4.11.0.86
      - opt-einsum==3.4.0
      - packaging==25.0
      - pillow==11.3.0
      - protobuf==4.25.8
      - pycparser==2.23
      - pyparsing==3.2.3
      - python-dateutil==2.9.0.post0
      - python-osc==1.8.3
      - python-rtmidi==1.5.8
      - rtmidi==2.5.0
      - scipy==1.13.1
      - sentencepiece==0.2.1
      - six==1.17.0
      - sounddevice==0.5.2
      - zipp==3.23.0
prefix: /Users/jeetajmani/miniconda3/envs/lab
